# A sample Gemfile
source "https://rubygems.org"

gem 'rubocop'
gem 'ruby-debug-ide'
gem 'debase'
gem 'rcodetools'
gem 'fastri'

gem 'sinatra'
gem 'sinatra-contrib'
gem "activerecord", "< 5.0.0"
gem 'sinatra-activerecord'

gem 'sqlite3', '~> 1.3.6'


group :production do
  gem 'pg'
end
